data = list(map(list, """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
""".strip().split("\n")))

with open("day7_input.txt") as f:
    data = list(map(list, f.read().strip().split("\n")))
# print(data)
kount = 0
for line in range(len(data)):
    for char in range(len(data[line])):
        if data[line][char] == "S":
            data[line+1][char] = "|"
        elif data[line][char] == "^" and data[line-1][char] == "|" and line != 0:
            kount+=1
            data[line][char-1], data[line][char+1] = "|", "|"
            # print("hi")
        elif data[line-1][char] == "|" and line != 0:
            data[line][char] = "|"
            # print("|", end="")
        else:
            # print(".", end="")
            continue
    print()

for line in data:
    print("".join(line))

print("Final Answer is -> : ", kount)
